name: CI/CD - API Automated Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  cypress-api-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress API Tests & Generate Report
        run: npm run report:api

      - name: Upload Mochawesome Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-api-execution-report
          path: cypress/reports