name: CI/CD - E2E & API Automated Tests

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  cypress-run:
    name: Run Cypress Suite (API + GUI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Suite & Generate Report
        run: npm run test:ci

      - name: Upload Mochawesome Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-execution-report
          path: cypress/reports
          retention-days: 7
